const express = require('express')
const app = express()
const cors = require('cors')
const userRoutes = require('./Routes/userRoutes')
const authRoutes = require('./Routes/authRoutes')
require('./config')
app.use(express.json())
app.use(cors())
app.use("/",userRoutes)
app.use("/",authRoutes)
app.listen(5000)